[package]
name = "mclone-server"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
mclone-core.workspace = true
mclone-blocks.workspace = true
mclone-light.workspace = true
mclone-physics = { workspace = true, optional = true }
mclone-protocol.workspace = true
mclone-worldgen.workspace = true

[features]
default = []
physics = ["dep:mclone-physics"]
physics-rapier = ["physics", "mclone-physics/rapier"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys.workspace = true
wasm-bindgen.workspace = true
web-sys = { workspace = true, features = [
  "ErrorEvent",
  "MessageEvent",
  "Worker",
  "WorkerOptions",
  "WorkerType",
] }

[dev-dependencies]
serde_json.workspace = true

[lib]
name = "mclone_server"
path = "src/lib.rs"
