import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

import { readLiquidScenario } from "../../src/oracle/integration/liquid-scenario.ts";

function usage(): never {
  process.stderr.write(
    "usage: prepare-liquid-server.ts --scenario <path> --work-dir <dir> --props-template <path> --eula-template <path>\n",
  );
  process.exit(2);
}

function parseArgs(argv: readonly string[]): Map<string, string> {
  const out = new Map<string, string>();
  for (let index = 0; index < argv.length; index++) {
    const arg = argv[index]!;
    if (!arg.startsWith("--")) {
      process.stderr.write(`expected --flag, got '${arg}'\n`);
      usage();
    }
    const name = arg.slice(2);
    if (index + 1 >= argv.length) {
      process.stderr.write(`missing value for --${name}\n`);
      usage();
    }
    out.set(name, argv[++index]!);
  }
  return out;
}

function requireArg(args: Map<string, string>, name: string): string {
  const value = args.get(name);
  if (value === undefined || value === "") {
    process.stderr.write(`missing required --${name}\n`);
    usage();
  }
  return value;
}

function writeText(path: string, content: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

function rewriteServerProperties(template: string, seed: string, generateStructures: boolean): string {
  const lines = template.split(/\r?\n/).map((line) => {
    if (line.startsWith("level-seed=")) {
      return `level-seed=${seed}`;
    }
    if (line.startsWith("generate-structures=")) {
      return `generate-structures=${generateStructures ? "true" : "false"}`;
    }
    if (line.startsWith("function-permission-level=")) {
      return "function-permission-level=4";
    }
    if (line.startsWith("view-distance=")) {
      return "view-distance=2";
    }
    if (line.startsWith("simulation-distance=")) {
      return "simulation-distance=2";
    }
    return line.replaceAll("__SEED__", seed);
  });
  return `${lines.join("\n")}\n`;
}

function mcfunction(lines: readonly string[]): string {
  return `${lines.join("\n")}\n`;
}

function main(): void {
  const args = parseArgs(process.argv.slice(2));
  const scenarioPath = resolve(requireArg(args, "scenario"));
  const workDir = resolve(requireArg(args, "work-dir"));
  const propsTemplatePath = resolve(requireArg(args, "props-template"));
  const eulaTemplatePath = resolve(requireArg(args, "eula-template"));
  const scenario = readLiquidScenario(scenarioPath);

  mkdirSync(workDir, { recursive: true });
  const propsTemplate = readFileSync(propsTemplatePath, "utf8");
  writeText(resolve(workDir, "server.properties"), rewriteServerProperties(propsTemplate, scenario.seed, scenario.generateStructures));
  writeText(resolve(workDir, "eula.txt"), readFileSync(eulaTemplatePath, "utf8"));

  const packRoot = resolve(workDir, "world/datapacks/mclone-liquid-oracle");
  writeText(
    resolve(packRoot, "pack.mcmeta"),
    JSON.stringify({ pack: { pack_format: 7, description: "mclone liquid oracle" } }, undefined, 2) + "\n",
  );
  writeText(
    resolve(packRoot, "data/minecraft/tags/functions/load.json"),
    JSON.stringify({ values: ["mclone_liquid:load"] }, undefined, 2) + "\n",
  );
  writeText(
    resolve(packRoot, "data/minecraft/tags/functions/tick.json"),
    JSON.stringify({ values: ["mclone_liquid:tick"] }, undefined, 2) + "\n",
  );

  const loadLines = [
    "# Generated by mclone Liquid0 oracle harness.",
    "gamerule randomTickSpeed 0",
    "gamerule doDaylightCycle false",
    "gamerule doWeatherCycle false",
    "gamerule doMobSpawning false",
    "time set noon",
    "scoreboard objectives add liquid_ticks dummy",
    "scoreboard players set elapsed liquid_ticks 0",
    ...scenario.commands,
  ];
  if (scenario.ticks === 0) {
    loadLines.push("save-all flush", "stop");
  }

  const tickLines = scenario.ticks === 0
    ? ["# Scenario stops from load function for ticks=0."]
    : [
      "# Generated by mclone Liquid0 oracle harness.",
      "scoreboard players add elapsed liquid_ticks 1",
      `execute if score elapsed liquid_ticks matches ${scenario.ticks} run save-all flush`,
      `execute if score elapsed liquid_ticks matches ${scenario.ticks} run stop`,
    ];

  writeText(resolve(packRoot, "data/mclone_liquid/functions/load.mcfunction"), mcfunction(loadLines));
  writeText(resolve(packRoot, "data/mclone_liquid/functions/tick.mcfunction"), mcfunction(tickLines));
}

try {
  main();
} catch (error) {
  process.stderr.write(`[prepare-liquid-server] ${(error as Error).message}\n`);
  process.exit(1);
}
