[package]
name = "mclone-web-client"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
glam.workspace = true
mclone-assets.workspace = true
mclone-client.workspace = true
mclone-core.workspace = true
mclone-mesh.workspace = true
mclone-net.workspace = true
mclone-protocol.workspace = true
mclone-render.workspace = true
mclone-render-session.workspace = true
mclone-server.workspace = true
js-sys.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
wgpu.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { workspace = true, features = [
  "console",
  "ErrorEvent",
  "HtmlCanvasElement",
  "MessageEvent",
  "Worker",
  "WorkerOptions",
  "WorkerType",
  "Window",
] }

[lib]
crate-type = ["cdylib", "rlib"]
name = "mclone_web_client"
path = "src/lib.rs"
