[package]
name = "mclone-render"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
glam.workspace = true
image.workspace = true
log.workspace = true
mclone-assets.workspace = true
mclone-core.workspace = true
mclone-diagnostics.workspace = true
mclone-mesh.workspace = true
mclone-ui.workspace = true
rustc-hash = "1"
serde.workspace = true
serde_json.workspace = true
wgpu.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pollster.workspace = true
winit.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys.workspace = true

[lib]
name = "mclone_render"
path = "src/lib.rs"
