[package]
name = "mclone-worldgen"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
mclone-core.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10"

[lib]
name = "mclone_worldgen"
path = "src/lib.rs"
