[package]
name = "mclone-native-client"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[features]
default = []
xr = [
    "dep:ash",
    "dep:libloading",
    "dep:metal",
    "dep:openxr",
    "dep:pollster",
    "dep:serde_json",
]

[dependencies]
anyhow.workspace = true
ash = { workspace = true, optional = true }
env_logger.workspace = true
glam.workspace = true
image.workspace = true
libloading = { workspace = true, optional = true }
log.workspace = true
mclone-assets.workspace = true
mclone-app-runtime.workspace = true
mclone-client.workspace = true
mclone-core.workspace = true
mclone-mesh.workspace = true
mclone-net.workspace = true
mclone-protocol.workspace = true
mclone-render.workspace = true
mclone-render-session.workspace = true
mclone-server.workspace = true
mclone-ui.workspace = true
openxr = { workspace = true, optional = true }
pollster = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
wgpu.workspace = true
winit.workspace = true

[target.'cfg(target_vendor = "apple")'.dependencies]
metal = { workspace = true, optional = true }

[[bin]]
name = "mclone-native-client"
path = "src/main.rs"
