[package]
name = "mclone-native-client"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
env_logger.workspace = true
glam.workspace = true
image.workspace = true
log.workspace = true
mclone-assets.workspace = true
mclone-client.workspace = true
mclone-core.workspace = true
mclone-mesh.workspace = true
mclone-net.workspace = true
mclone-protocol.workspace = true
mclone-render.workspace = true
mclone-server.workspace = true
mclone-ui.workspace = true
wgpu.workspace = true
winit.workspace = true

[[bin]]
name = "mclone-native-client"
path = "src/main.rs"
