use super::*;

pub(super) const LOW_VISIBILITY_FEATURE_CASES: &[LowVisibilityFeatureCase] = &[
    LowVisibilityFeatureCase {
        seed: 16,
        chunk_x: 1,
        chunk_z: -1,
        biome_key: "minecraft:plains",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 233,
        chunk_x: -1,
        chunk_z: 0,
        biome_key: "minecraft:taiga",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 2 },
    },
    LowVisibilityFeatureCase {
        seed: 978,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:mushroom_fields",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 2 },
    },
    LowVisibilityFeatureCase {
        seed: 74,
        chunk_x: -7,
        chunk_z: -12,
        biome_key: "minecraft:mushroom_field_shore",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 2 },
    },
    LowVisibilityFeatureCase {
        seed: 19,
        chunk_x: -12,
        chunk_z: -12,
        biome_key: "minecraft:giant_tree_taiga",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 19,
        chunk_x: -12,
        chunk_z: -7,
        biome_key: "minecraft:giant_tree_taiga_hills",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 132,
        chunk_x: 10,
        chunk_z: 0,
        biome_key: "minecraft:giant_spruce_taiga",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 6 },
    },
    LowVisibilityFeatureCase {
        seed: 93,
        chunk_x: -11,
        chunk_z: -10,
        biome_key: "minecraft:giant_spruce_taiga_hills",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 3 },
    },
    LowVisibilityFeatureCase {
        seed: 3,
        chunk_x: -11,
        chunk_z: 4,
        biome_key: "minecraft:mountains",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 3,
        chunk_x: 0,
        chunk_z: -1,
        biome_key: "minecraft:wooded_mountains",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 9,
        chunk_x: 9,
        chunk_z: 9,
        biome_key: "minecraft:modified_gravelly_mountains",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 25,
        chunk_x: -3,
        chunk_z: 7,
        biome_key: "minecraft:sunflower_plains",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 2 },
    },
    LowVisibilityFeatureCase {
        seed: 1,
        chunk_x: 0,
        chunk_z: -7,
        biome_key: "minecraft:forest",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 2 },
    },
    LowVisibilityFeatureCase {
        seed: 1,
        chunk_x: -1,
        chunk_z: -11,
        biome_key: "minecraft:wooded_hills",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 2 },
    },
    LowVisibilityFeatureCase {
        seed: 20,
        chunk_x: 11,
        chunk_z: 0,
        biome_key: "minecraft:flower_forest",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 7,
        chunk_x: -5,
        chunk_z: -5,
        biome_key: "minecraft:birch_forest",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 7,
        chunk_x: -9,
        chunk_z: -12,
        biome_key: "minecraft:birch_forest_hills",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 39,
        chunk_x: 5,
        chunk_z: -12,
        biome_key: "minecraft:tall_birch_forest",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 7 },
    },
    LowVisibilityFeatureCase {
        seed: 32,
        chunk_x: -6,
        chunk_z: 4,
        biome_key: "minecraft:tall_birch_hills",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 5 },
    },
    LowVisibilityFeatureCase {
        seed: 0,
        chunk_x: -7,
        chunk_z: 8,
        biome_key: "minecraft:dark_forest",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 2 },
    },
    LowVisibilityFeatureCase {
        seed: 123,
        chunk_x: 1,
        chunk_z: 7,
        biome_key: "minecraft:dark_forest_hills",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 2,
        chunk_x: -12,
        chunk_z: 12,
        biome_key: "minecraft:taiga_hills",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 201,
        chunk_x: 1,
        chunk_z: -6,
        biome_key: "minecraft:taiga_mountains",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 2 },
    },
    LowVisibilityFeatureCase {
        seed: 14,
        chunk_x: -10,
        chunk_z: -12,
        biome_key: "minecraft:snowy_tundra",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 42,
        chunk_x: -11,
        chunk_z: -6,
        biome_key: "minecraft:snowy_mountains",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 14,
        chunk_x: -12,
        chunk_z: 10,
        biome_key: "minecraft:snowy_taiga",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 3 },
    },
    LowVisibilityFeatureCase {
        seed: 14,
        chunk_x: -12,
        chunk_z: -7,
        biome_key: "minecraft:snowy_taiga_hills",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 14,
        chunk_x: -5,
        chunk_z: 10,
        biome_key: "minecraft:snowy_taiga_mountains",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 123,
        chunk_x: -4,
        chunk_z: 10,
        biome_key: "minecraft:gravelly_mountains",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 5 },
    },
    LowVisibilityFeatureCase {
        seed: 59,
        chunk_x: -12,
        chunk_z: -11,
        biome_key: "minecraft:ice_spikes",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 3 },
    },
    LowVisibilityFeatureCase {
        seed: 33,
        chunk_x: -10,
        chunk_z: -14,
        biome_key: "minecraft:savanna",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 38,
        chunk_x: -3,
        chunk_z: -15,
        biome_key: "minecraft:savanna_plateau",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 68,
        chunk_x: -6,
        chunk_z: 3,
        biome_key: "minecraft:shattered_savanna",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 3 },
    },
    LowVisibilityFeatureCase {
        seed: 126,
        chunk_x: 13,
        chunk_z: 14,
        biome_key: "minecraft:shattered_savanna_plateau",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 1,
        chunk_x: 12,
        chunk_z: 1,
        biome_key: "minecraft:jungle",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 2 },
    },
    LowVisibilityFeatureCase {
        seed: 1,
        chunk_x: 15,
        chunk_z: 2,
        biome_key: "minecraft:jungle_hills",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 149,
        chunk_x: 4,
        chunk_z: 13,
        biome_key: "minecraft:jungle_edge",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 102,
        chunk_x: -13,
        chunk_z: -12,
        biome_key: "minecraft:modified_jungle",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 8201,
        chunk_x: 6,
        chunk_z: -8,
        biome_key: "minecraft:modified_jungle_edge",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 3 },
    },
    LowVisibilityFeatureCase {
        seed: 71,
        chunk_x: 9,
        chunk_z: 0,
        biome_key: "minecraft:bamboo_jungle",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 102,
        chunk_x: -1,
        chunk_z: -16,
        biome_key: "minecraft:bamboo_jungle_hills",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 1,
        chunk_x: 8,
        chunk_z: -13,
        biome_key: "minecraft:river",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 66,
        chunk_x: -11,
        chunk_z: -1,
        biome_key: "minecraft:frozen_river",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 1,
        chunk_x: -14,
        chunk_z: -11,
        biome_key: "minecraft:beach",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 3 },
    },
    LowVisibilityFeatureCase {
        seed: 54,
        chunk_x: 8,
        chunk_z: 4,
        biome_key: "minecraft:snowy_beach",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 0,
        chunk_x: 8,
        chunk_z: 16,
        biome_key: "minecraft:stone_shore",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 5 },
    },
    LowVisibilityFeatureCase {
        seed: 3,
        chunk_x: -16,
        chunk_z: -3,
        biome_key: "minecraft:swamp",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 10 },
    },
    LowVisibilityFeatureCase {
        seed: 92,
        chunk_x: -5,
        chunk_z: 13,
        biome_key: "minecraft:swamp_hills",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 3 },
    },
    LowVisibilityFeatureCase {
        seed: 0,
        chunk_x: -10,
        chunk_z: -16,
        biome_key: "minecraft:badlands",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 51,
        chunk_x: 12,
        chunk_z: -16,
        biome_key: "minecraft:wooded_badlands_plateau",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 2 },
    },
    LowVisibilityFeatureCase {
        seed: 28,
        chunk_x: -2,
        chunk_z: -16,
        biome_key: "minecraft:badlands_plateau",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 86,
        chunk_x: -16,
        chunk_z: -2,
        biome_key: "minecraft:eroded_badlands",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 84,
        chunk_x: -13,
        chunk_z: -2,
        biome_key: "minecraft:modified_wooded_badlands_plateau",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 1150,
        chunk_x: -15,
        chunk_z: 13,
        biome_key: "minecraft:modified_badlands_plateau",
        expectation: LowVisibilityFeatureExpectation::VisibleSmallMushrooms { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 132,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:giant_tree_taiga",
        expectation: LowVisibilityFeatureExpectation::ForestRockBoulders { min_count: 8 },
    },
    LowVisibilityFeatureCase {
        seed: 61,
        chunk_x: 1,
        chunk_z: 2,
        biome_key: "minecraft:jungle",
        expectation: LowVisibilityFeatureExpectation::JungleCocoaVines {
            min_cocoa: 1,
            min_vines: 1,
        },
    },
    LowVisibilityFeatureCase {
        seed: 61,
        chunk_x: 1,
        chunk_z: 2,
        biome_key: "minecraft:jungle",
        expectation: LowVisibilityFeatureExpectation::JungleBushShape { min_matches: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 211,
        chunk_x: -2,
        chunk_z: 1,
        biome_key: "minecraft:swamp",
        expectation: LowVisibilityFeatureExpectation::VisiblePumpkins { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 74_739,
        chunk_x: 3,
        chunk_z: 5,
        biome_key: "minecraft:stone_shore",
        expectation: LowVisibilityFeatureExpectation::VisiblePumpkins { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 58,
        chunk_x: 2,
        chunk_z: 1,
        biome_key: "minecraft:river",
        expectation: LowVisibilityFeatureExpectation::VisiblePumpkins { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 326,
        chunk_x: -4,
        chunk_z: 6,
        biome_key: "minecraft:frozen_river",
        expectation: LowVisibilityFeatureExpectation::VisiblePumpkins { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 349,
        chunk_x: -7,
        chunk_z: -5,
        biome_key: "minecraft:beach",
        expectation: LowVisibilityFeatureExpectation::VisiblePumpkins { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 2805,
        chunk_x: 14,
        chunk_z: 6,
        biome_key: "minecraft:snowy_beach",
        expectation: LowVisibilityFeatureExpectation::VisiblePumpkins { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 3407,
        chunk_x: 7,
        chunk_z: -2,
        biome_key: "minecraft:swamp_hills",
        expectation: LowVisibilityFeatureExpectation::VisiblePumpkins { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 25,
        chunk_x: -8,
        chunk_z: -2,
        biome_key: "minecraft:sunflower_plains",
        expectation: LowVisibilityFeatureExpectation::VisiblePumpkins { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 327,
        chunk_x: -6,
        chunk_z: 6,
        biome_key: "minecraft:desert",
        expectation: LowVisibilityFeatureExpectation::VisiblePumpkins { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 2768,
        chunk_x: -5,
        chunk_z: -7,
        biome_key: "minecraft:desert_hills",
        expectation: LowVisibilityFeatureExpectation::VisiblePumpkins { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 5012,
        chunk_x: 13,
        chunk_z: -10,
        biome_key: "minecraft:desert_lakes",
        expectation: LowVisibilityFeatureExpectation::VisiblePumpkins { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 2336,
        chunk_x: -5,
        chunk_z: -7,
        biome_key: "minecraft:badlands",
        expectation: LowVisibilityFeatureExpectation::VisiblePumpkins { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 1248,
        chunk_x: -6,
        chunk_z: 8,
        biome_key: "minecraft:wooded_badlands_plateau",
        expectation: LowVisibilityFeatureExpectation::VisiblePumpkins { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 653,
        chunk_x: -5,
        chunk_z: 6,
        biome_key: "minecraft:badlands_plateau",
        expectation: LowVisibilityFeatureExpectation::VisiblePumpkins { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 85_720,
        chunk_x: 11,
        chunk_z: 5,
        biome_key: "minecraft:eroded_badlands",
        expectation: LowVisibilityFeatureExpectation::VisiblePumpkins { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 13_518,
        chunk_x: 10,
        chunk_z: -3,
        biome_key: "minecraft:modified_wooded_badlands_plateau",
        expectation: LowVisibilityFeatureExpectation::VisiblePumpkins { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 168_856,
        chunk_x: 4,
        chunk_z: 10,
        biome_key: "minecraft:modified_badlands_plateau",
        expectation: LowVisibilityFeatureExpectation::VisiblePumpkins { min_count: 1 },
    },
    LowVisibilityFeatureCase {
        seed: 62,
        chunk_x: 3,
        chunk_z: 1,
        biome_key: "minecraft:savanna",
        expectation: LowVisibilityFeatureExpectation::DefaultSpringVisibleFluids {
            min_water_blocks: 2,
            min_lava_blocks: 1,
        },
    },
    LowVisibilityFeatureCase {
        seed: 43,
        chunk_x: -1,
        chunk_z: 1,
        biome_key: "minecraft:sunflower_plains",
        expectation: LowVisibilityFeatureExpectation::DefaultSpringVisibleFluids {
            min_water_blocks: 1,
            min_lava_blocks: 1,
        },
    },
];
