use super::*;

pub(super) const PALETTE_MATRIX_CASES: &[PaletteMatrixCase] = &[
    PaletteMatrixCase {
        seed: 1,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:ocean",
        surface_family: SurfaceFamily::Water,
        feature_family: Some(FeatureFamily::OceanWaterPlants),
    },
    PaletteMatrixCase {
        seed: 16,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:plains",
        surface_family: SurfaceFamily::Grass,
        feature_family: Some(FeatureFamily::PlainsVegetation),
    },
    PaletteMatrixCase {
        seed: 258,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:desert",
        surface_family: SurfaceFamily::Sand,
        feature_family: Some(FeatureFamily::DesertDeadBushCactusSugarCane),
    },
    PaletteMatrixCase {
        seed: 33,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:mountains",
        surface_family: SurfaceFamily::Mountain,
        feature_family: Some(FeatureFamily::MountainTrees),
    },
    PaletteMatrixCase {
        seed: 0,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:forest",
        surface_family: SurfaceFamily::Grass,
        feature_family: Some(FeatureFamily::ForestOakBirchTrees),
    },
    PaletteMatrixCase {
        seed: 18_918,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:swamp",
        surface_family: SurfaceFamily::Swamp,
        feature_family: Some(FeatureFamily::SwampNativeSubsetSugarCaneLilyPad),
    },
    PaletteMatrixCase {
        seed: 39,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:river",
        surface_family: SurfaceFamily::Water,
        feature_family: Some(FeatureFamily::RiverSeagrass),
    },
    PaletteMatrixCase {
        seed: 779,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:frozen_ocean",
        surface_family: SurfaceFamily::FrozenWater,
        feature_family: Some(FeatureFamily::FrozenOceanIcebergs),
    },
    PaletteMatrixCase {
        seed: 44,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:dark_forest",
        surface_family: SurfaceFamily::Grass,
        feature_family: Some(FeatureFamily::DarkForestCanopyMushrooms),
    },
    PaletteMatrixCase {
        seed: 25_122,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:snowy_taiga",
        surface_family: SurfaceFamily::Snow,
        feature_family: Some(FeatureFamily::TaigaSpruceFernBerry),
    },
    PaletteMatrixCase {
        seed: 132,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:giant_tree_taiga",
        surface_family: SurfaceFamily::GiantTaiga,
        feature_family: Some(FeatureFamily::GiantTaigaSpruceTrees),
    },
    PaletteMatrixCase {
        seed: 978,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:mushroom_fields",
        surface_family: SurfaceFamily::Mycelium,
        feature_family: Some(FeatureFamily::MushroomFieldHugeMushrooms),
    },
    PaletteMatrixCase {
        seed: 1941,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:beach",
        surface_family: SurfaceFamily::Sand,
        feature_family: Some(FeatureFamily::DefaultExtraSugarCane),
    },
    PaletteMatrixCase {
        seed: 5006,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:snowy_beach",
        surface_family: SurfaceFamily::SnowySand,
        feature_family: Some(FeatureFamily::DefaultExtraSugarCane),
    },
    PaletteMatrixCase {
        seed: 71,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:jungle",
        surface_family: SurfaceFamily::Grass,
        feature_family: Some(FeatureFamily::JungleTrees),
    },
    PaletteMatrixCase {
        seed: 2235,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:jungle_edge",
        surface_family: SurfaceFamily::Grass,
        feature_family: Some(FeatureFamily::JungleTrees),
    },
    PaletteMatrixCase {
        seed: 10,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:birch_forest",
        surface_family: SurfaceFamily::Grass,
        feature_family: Some(FeatureFamily::BirchTrees),
    },
    PaletteMatrixCase {
        seed: 233,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:taiga",
        surface_family: SurfaceFamily::Grass,
        feature_family: Some(FeatureFamily::TaigaSpruceFernBerry),
    },
    PaletteMatrixCase {
        seed: 42,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:snowy_tundra",
        surface_family: SurfaceFamily::Snow,
        feature_family: Some(FeatureFamily::SnowySpruceFern),
    },
    PaletteMatrixCase {
        seed: 28,
        chunk_x: -2,
        chunk_z: -8,
        biome_key: "minecraft:badlands",
        surface_family: SurfaceFamily::Badlands,
        feature_family: Some(FeatureFamily::BadlandsDeadBushCactusSugarCane),
    },
    PaletteMatrixCase {
        seed: 2696,
        chunk_x: -14,
        chunk_z: -14,
        biome_key: "minecraft:warm_ocean",
        surface_family: SurfaceFamily::Water,
        feature_family: Some(FeatureFamily::WarmOceanCoralSeaPickles),
    },
    PaletteMatrixCase {
        seed: 6,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:lukewarm_ocean",
        surface_family: SurfaceFamily::Water,
        feature_family: Some(FeatureFamily::OceanWaterPlants),
    },
    PaletteMatrixCase {
        seed: 5,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:cold_ocean",
        surface_family: SurfaceFamily::Water,
        feature_family: Some(FeatureFamily::OceanWaterPlants),
    },
    PaletteMatrixCase {
        seed: 1679,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:deep_frozen_ocean",
        surface_family: SurfaceFamily::FrozenWater,
        feature_family: Some(FeatureFamily::FrozenOceanIcebergs),
    },
    PaletteMatrixCase {
        seed: 6232,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:giant_spruce_taiga",
        surface_family: SurfaceFamily::GiantTaiga,
        feature_family: Some(FeatureFamily::GiantTaigaSpruceTrees),
    },
    PaletteMatrixCase {
        seed: 33,
        chunk_x: -2,
        chunk_z: -4,
        biome_key: "minecraft:savanna",
        surface_family: SurfaceFamily::Grass,
        feature_family: Some(FeatureFamily::SavannaAcacia),
    },
    PaletteMatrixCase {
        seed: 126,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:savanna_plateau",
        surface_family: SurfaceFamily::Grass,
        feature_family: Some(FeatureFamily::SavannaAcacia),
    },
    PaletteMatrixCase {
        seed: 68,
        chunk_x: -6,
        chunk_z: 0,
        biome_key: "minecraft:shattered_savanna",
        surface_family: SurfaceFamily::ShatteredSavanna,
        feature_family: Some(FeatureFamily::SavannaAcacia),
    },
    PaletteMatrixCase {
        seed: 252,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:frozen_river",
        surface_family: SurfaceFamily::FrozenWater,
        feature_family: Some(FeatureFamily::DefaultExtraSugarCane),
    },
    PaletteMatrixCase {
        seed: 326,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:snowy_mountains",
        surface_family: SurfaceFamily::Snow,
        feature_family: Some(FeatureFamily::SnowySpruceFern),
    },
    PaletteMatrixCase {
        seed: 7056,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:mushroom_field_shore",
        surface_family: SurfaceFamily::Mycelium,
        feature_family: Some(FeatureFamily::MushroomFieldHugeMushrooms),
    },
    PaletteMatrixCase {
        seed: 348,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:desert_hills",
        surface_family: SurfaceFamily::Sand,
        feature_family: Some(FeatureFamily::DesertDeadBushCactusSugarCane),
    },
    PaletteMatrixCase {
        seed: 2,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:wooded_hills",
        surface_family: SurfaceFamily::Grass,
        feature_family: Some(FeatureFamily::ForestOakBirchTrees),
    },
    PaletteMatrixCase {
        seed: 29,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:taiga_hills",
        surface_family: SurfaceFamily::Grass,
        feature_family: Some(FeatureFamily::TaigaSpruceFernBerry),
    },
    PaletteMatrixCase {
        seed: 146,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:jungle_hills",
        surface_family: SurfaceFamily::Grass,
        feature_family: Some(FeatureFamily::JungleTrees),
    },
    PaletteMatrixCase {
        seed: 4,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:deep_ocean",
        surface_family: SurfaceFamily::Water,
        feature_family: Some(FeatureFamily::OceanWaterPlants),
    },
    PaletteMatrixCase {
        seed: 74739,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:stone_shore",
        surface_family: SurfaceFamily::Mountain,
        feature_family: Some(FeatureFamily::DefaultExtraSugarCane),
    },
    PaletteMatrixCase {
        seed: 30,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:birch_forest_hills",
        surface_family: SurfaceFamily::Grass,
        feature_family: Some(FeatureFamily::BirchTrees),
    },
    PaletteMatrixCase {
        seed: 18_930,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:snowy_taiga_hills",
        surface_family: SurfaceFamily::Snow,
        feature_family: Some(FeatureFamily::TaigaSpruceFernBerry),
    },
    PaletteMatrixCase {
        seed: 305,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:giant_tree_taiga_hills",
        surface_family: SurfaceFamily::GiantTaiga,
        feature_family: Some(FeatureFamily::GiantTaigaSpruceTrees),
    },
    PaletteMatrixCase {
        seed: 58,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:wooded_mountains",
        surface_family: SurfaceFamily::Mountain,
        feature_family: Some(FeatureFamily::MountainTrees),
    },
    PaletteMatrixCase {
        seed: 4764,
        chunk_x: 6,
        chunk_z: -3,
        biome_key: "minecraft:wooded_badlands_plateau",
        surface_family: SurfaceFamily::Badlands,
        feature_family: Some(FeatureFamily::WoodedBadlandsTrees),
    },
    PaletteMatrixCase {
        seed: 947,
        chunk_x: -6,
        chunk_z: -2,
        biome_key: "minecraft:badlands_plateau",
        surface_family: SurfaceFamily::Badlands,
        feature_family: Some(FeatureFamily::BadlandsDeadBushCactusSugarCane),
    },
    PaletteMatrixCase {
        seed: 56,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:deep_lukewarm_ocean",
        surface_family: SurfaceFamily::Water,
        feature_family: Some(FeatureFamily::OceanWaterPlants),
    },
    PaletteMatrixCase {
        seed: 13,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:deep_cold_ocean",
        surface_family: SurfaceFamily::Water,
        feature_family: Some(FeatureFamily::OceanWaterPlants),
    },
    PaletteMatrixCase {
        seed: 43,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:sunflower_plains",
        surface_family: SurfaceFamily::Grass,
        feature_family: Some(FeatureFamily::SunflowerPlainsSunflowers),
    },
    PaletteMatrixCase {
        seed: 98,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:desert_lakes",
        surface_family: SurfaceFamily::Sand,
        feature_family: Some(FeatureFamily::DesertDeadBushCactusSugarCane),
    },
    PaletteMatrixCase {
        seed: 250,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:gravelly_mountains",
        surface_family: SurfaceFamily::Mountain,
        feature_family: Some(FeatureFamily::MountainTrees),
    },
    PaletteMatrixCase {
        seed: 135,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:flower_forest",
        surface_family: SurfaceFamily::Grass,
        feature_family: Some(FeatureFamily::FlowerForestFlowers),
    },
    PaletteMatrixCase {
        seed: 6126,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:taiga_mountains",
        surface_family: SurfaceFamily::Grass,
        feature_family: Some(FeatureFamily::TaigaSpruceFernBerry),
    },
    PaletteMatrixCase {
        seed: 89_335,
        chunk_x: 5,
        chunk_z: 4,
        biome_key: "minecraft:swamp_hills",
        surface_family: SurfaceFamily::Swamp,
        feature_family: Some(FeatureFamily::SwampNativeSubsetSugarCaneLilyPad),
    },
    PaletteMatrixCase {
        seed: 59,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:ice_spikes",
        surface_family: SurfaceFamily::Snow,
        feature_family: Some(FeatureFamily::IceSpikesPackedIce),
    },
    PaletteMatrixCase {
        seed: 1374,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:modified_jungle",
        surface_family: SurfaceFamily::Grass,
        feature_family: Some(FeatureFamily::JungleTrees),
    },
    PaletteMatrixCase {
        seed: 314_096,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:modified_jungle_edge",
        surface_family: SurfaceFamily::Grass,
        feature_family: Some(FeatureFamily::SparseJungleTrees),
    },
    PaletteMatrixCase {
        seed: 48,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:tall_birch_forest",
        surface_family: SurfaceFamily::Grass,
        feature_family: Some(FeatureFamily::BirchTrees),
    },
    PaletteMatrixCase {
        seed: 1557,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:tall_birch_hills",
        surface_family: SurfaceFamily::Grass,
        feature_family: Some(FeatureFamily::BirchTrees),
    },
    PaletteMatrixCase {
        seed: 410,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:dark_forest_hills",
        surface_family: SurfaceFamily::Grass,
        feature_family: Some(FeatureFamily::DarkForestCanopyMushrooms),
    },
    PaletteMatrixCase {
        seed: 12_006,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:snowy_taiga_mountains",
        surface_family: SurfaceFamily::Snow,
        feature_family: Some(FeatureFamily::SnowySpruceFern),
    },
    PaletteMatrixCase {
        seed: 282,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:giant_spruce_taiga_hills",
        surface_family: SurfaceFamily::GiantTaiga,
        feature_family: Some(FeatureFamily::GiantTaigaSpruceTrees),
    },
    PaletteMatrixCase {
        seed: 1831,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:modified_gravelly_mountains",
        surface_family: SurfaceFamily::Mountain,
        feature_family: Some(FeatureFamily::MountainTrees),
    },
    PaletteMatrixCase {
        seed: 153,
        chunk_x: -8,
        chunk_z: -2,
        biome_key: "minecraft:shattered_savanna_plateau",
        surface_family: SurfaceFamily::ShatteredSavanna,
        feature_family: Some(FeatureFamily::SavannaAcacia),
    },
    PaletteMatrixCase {
        seed: 868,
        chunk_x: 7,
        chunk_z: -8,
        biome_key: "minecraft:eroded_badlands",
        surface_family: SurfaceFamily::Badlands,
        feature_family: Some(FeatureFamily::BadlandsDeadBushCactusSugarCane),
    },
    PaletteMatrixCase {
        seed: 12_115,
        chunk_x: 0,
        chunk_z: -1,
        biome_key: "minecraft:modified_wooded_badlands_plateau",
        surface_family: SurfaceFamily::Badlands,
        feature_family: Some(FeatureFamily::WoodedBadlandsTrees),
    },
    PaletteMatrixCase {
        seed: 1150,
        chunk_x: -7,
        chunk_z: 1,
        biome_key: "minecraft:modified_badlands_plateau",
        surface_family: SurfaceFamily::Badlands,
        feature_family: Some(FeatureFamily::BadlandsDeadBushCactusSugarCane),
    },
    PaletteMatrixCase {
        seed: 1263,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:bamboo_jungle",
        surface_family: SurfaceFamily::Grass,
        feature_family: Some(FeatureFamily::BambooJungle),
    },
    PaletteMatrixCase {
        seed: 1000,
        chunk_x: 0,
        chunk_z: 0,
        biome_key: "minecraft:bamboo_jungle_hills",
        surface_family: SurfaceFamily::Grass,
        feature_family: Some(FeatureFamily::BambooJungle),
    },
];
