[package]
name = "mclone-client"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
mclone-assets.workspace = true
mclone-blocks.workspace = true
mclone-core.workspace = true
mclone-light.workspace = true
mclone-path.workspace = true
mclone-protocol.workspace = true
mclone-season.workspace = true

[lib]
name = "mclone_client"
path = "src/lib.rs"
