[package]
name = "mclone-mesh"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
image.workspace = true
mclone-assets.workspace = true
mclone-core.workspace = true
mclone-light.workspace = true
sha2 = "0.10"

[dev-dependencies]
serde_json.workspace = true

[lib]
name = "mclone_mesh"
path = "src/lib.rs"
