export namespace GenerationStep {
  export enum Decoration {
    RAW_GENERATION,
    LAKES,
    LOCAL_MODIFICATIONS,
    UNDERGROUND_STRUCTURES,
    SURFACE_STRUCTURES,
    STRONGHOLDS,
    UNDERGROUND_ORES,
    UNDERGROUND_DECORATION,
    VEGETAL_DECORATION,
    TOP_LAYER_MODIFICATION,
  }

  export const DECORATION_VALUES = [
    Decoration.RAW_GENERATION,
    Decoration.LAKES,
    Decoration.LOCAL_MODIFICATIONS,
    Decoration.UNDERGROUND_STRUCTURES,
    Decoration.SURFACE_STRUCTURES,
    Decoration.STRONGHOLDS,
    Decoration.UNDERGROUND_ORES,
    Decoration.UNDERGROUND_DECORATION,
    Decoration.VEGETAL_DECORATION,
    Decoration.TOP_LAYER_MODIFICATION,
  ] as const;
}
